### ISSUE TITLE
Recursive child selectors not working

### ISSUE THREAD

**Issue by bboyle1234** [Tyrrrz/LtGt#6]
```csharp
var url = "https://finance.yahoo.com/calendar/earnings?day=2019-02-04&offset=0&size=100";
var html = new WebClient().DownloadString(url);
var doc = HtmlParser.Default.ParseDocument(html);
var pagingSpan = doc.GetElementsBySelector(@"#fin-cal-table > h3 > span.Mstart\(15px\).Fw\(500\).Fz\(s\) > span").FirstOrDefault();
```

Problem is this selects span #1 shown in the image below instead of span #2 

![image](https://user-images.githubusercontent.com/1445862/63402430-6c936880-c3a9-11e9-907d-44c90dcb6501.png)

**Comment by bboyle1234** [comment]
I copied the selector string out of chrome by right-clicking on the span I wanted and choosing `Copy --> Selector`

**Comment by bboyle1234** [comment]
Here is the page source as seen in chrome view-source: 

![image](https://user-images.githubusercontent.com/1445862/63402744-8ed9b600-c3aa-11e9-8b34-a6722a53a529.png)

**Comment by Tyrrrz** [comment]
Those are really weird class names that they're using.

>`GetElementsBySelector(@"#fin-cal-table > h3 > span.Mstart\(15px\).Fw\(500\).Fz\(s\) > span")`

Can you try without backslashes?

**Comment by Tyrrrz** [comment]
Got around to testing this, looks like recursive child selectors are not working currently
