### ISSUE TITLE
ParseException

### ISSUE THREAD

**Issue by thatbakamono** [Tyrrrz/LtGt#8]
I've encountered a weird problem, it's probably due to some anti-parse protection. Could you please fix it?

https://hastebin.com/ceberekeji.hs

**Comment by Tyrrrz** [comment]
Can you also please give me the HTML source?

**Comment by Tyrrrz** [comment]
Ah, I see the problem seems to be in the fact that the tag name has dashes in it: `x-star-rating`.
Looks like [it's part of the standard now](https://html.spec.whatwg.org/multipage/custom-elements.html#custom-elements) so I'll fix it.
